apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dp-service
  labels:
   app: my-app
spec:
 replicas: 3
 selector:
  matchLabels:
   app: my-app
 template:
  metadata:
   labels:
    app: my-app
  spec:
   containers:
    - name: my-container
      image: tomcat
      ports:
       - containerPort: 8080
  