apiVersion: v1
kind: Service
metadata:
  name: my-np-service
  
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30000
      protocol: TCP
